name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v1.0.1, etc.

env:
  REGISTRY: docker.io
  IMAGE_NAME: ignition-comfyui

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # Remove tool cache (saves ~15 GB)
        tool-cache: true
        # Remove Android SDK (saves ~11 GB)
        android: true
        # Remove .NET (saves ~2 GB)
        dotnet: true
        # Remove Haskell (saves ~2.7 GB)
        haskell: true
        # Keep large packages that might be needed
        large-packages: false
        # Remove Docker images (saves space but we need Docker)
        docker-images: false
        
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=tag
          type=raw,value=latest,enable={{is_default_branch}}
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        # Optimize for space and speed
        build-args: |
          BUILDKIT_INLINE_CACHE=1
        
    - name: Image digest
      run: echo ${{ steps.meta.outputs.digest }}